# Generated by Django 3.0 on 2020-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0002_auto_20200407_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='department',
        ),
    ]
