# Generated by Django 3.0 on 2020-04-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0004_folder_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='department',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suiteapp.Department'),
        ),
    ]
