# Generated by Django 3.0 on 2020-04-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0007_auto_20200408_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='department',
        ),
    ]
