# Generated by Django 3.0 on 2020-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0013_auto_20200412_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_members',
            name='members',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
