# Generated by Django 3.0 on 2020-04-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0015_site_members_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_members',
        ),
    ]
