# Generated by Django 3.0 on 2020-04-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0018_auto_20200412_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUsers',
            new_name='SiteUser',
        ),
    ]
