# Generated by Django 3.0 on 2020-04-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0019_auto_20200412_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suiteapp.Department'),
        ),
        migrations.AlterField(
            model_name='file',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suiteapp.Faculty'),
        ),
    ]
