# Generated by Django 3.0 on 2020-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0020_auto_20200413_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
    ]
