# Generated by Django 3.0 on 2020-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0022_auto_20200415_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
