# Generated by Django 3.0 on 2020-04-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0024_auto_20200418_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_file',
        ),
        migrations.AddField(
            model_name='file',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
