# Generated by Django 3.0 on 2020-04-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0026_auto_20200419_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
