# Generated by Django 3.0 on 2020-04-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0027_folder_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder_path',
        ),
        migrations.AddField(
            model_name='folder',
            name='main_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suiteapp.Folder'),
        ),
    ]
