# Generated by Django 3.0 on 2020-05-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiteapp', '0028_auto_20200428_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
